### ISSUE TITLE
Put plotting into an  extension ?

### ISSUE THREAD

**Issue by j-fu** [WIAS-PDELib/ExtendableFEMBase.jl#5]
This would remove UnicodePlots as a strong dependency and remove some compilation time for users.

**Comment by chmerdon** [comment]
Yes, that's a good idea. Will do this.

**Comment by chmerdon** [comment]
Ok, I am running into a subtle issue:
- for the plots I require UnicodePlots and Term

When I do

> [weakdeps]
> UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
> Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
> 
> [extensions]
> ExtendableFEMBaseUnicodePlotsExt = "UnicodePlots"

Term is not found during compilation of the extension. How can I make term another dependency of the extension?
(If I move Term back to the main dependencies I get a stale dependency error from Aqua.)

**Comment by j-fu** [comment]
Ah need to think about this. Need to think about this. 
May be related to https://github.com/JuliaLang/julia/pull/56368 ?

**Comment by chmerdon** [comment]
Ok, it works in principle with

ExtendableFEMBaseUnicodePlotsExt = ["UnicodePlots", "Term"]

but then the user needs to use both packages to trigger that the extension is loaded. It would be more convenient that only UnicodePlots needs to be used...

**Comment by chmerdon** [comment]
Ok, for now I have switched off the line that requires Term. The extension seems to work now and only requires UnicodePlots.

**Comment by jpthiele** [comment]
@chmerdon seems like this is done, right?
If not feel free to reopen the issue.
